using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OF.FSimMan.Database.Migrations
{
    /// <inheritdoc />
    public partial class MigrationToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Disable Foreign Keys to allow table reconstruction
            migrationBuilder.Sql("PRAGMA foreign_keys = OFF;");

            // 2. Create the New Tables with Guid (TEXT) IDs based on Snapshot
            migrationBuilder.Sql(@"CREATE TABLE AppSettings_New (
        Id TEXT NOT NULL PRIMARY KEY,
        ApplicationMode INTEGER NOT NULL,
        CreatedAt TEXT NOT NULL,
        LastModifiedAt TEXT NOT NULL,
        LastSelectedView TEXT NOT NULL
    );");

            migrationBuilder.Sql(@"CREATE TABLE GameSettings_New (
        Id TEXT NOT NULL PRIMARY KEY,
        AppSettingsId TEXT NOT NULL,
        CreatedAt TEXT NOT NULL,
        DataDirectoryPath TEXT NOT NULL,
        Discriminator TEXT NOT NULL,
        ExeDirectoryPath TEXT NOT NULL,
        Game INTEGER NOT NULL,
        GameOrigin INTEGER NOT NULL,
        IsAutogeneratedModPackExecuted INTEGER NOT NULL,
        IsEnabled INTEGER NOT NULL,
        LastModifiedAt TEXT NOT NULL,
        FOREIGN KEY (AppSettingsId) REFERENCES AppSettings_New (Id) ON DELETE CASCADE
    );");

            migrationBuilder.Sql(@"CREATE TABLE GameStartArguments_New (
        Id TEXT NOT NULL PRIMARY KEY,
        CreatedAt TEXT NOT NULL,
        DisableFrameLimit INTEGER NOT NULL,
        EnableCheats INTEGER NOT NULL,
        GameSettingsId TEXT NOT NULL,
        LastModifiedAt TEXT NOT NULL,
        SkipIntros INTEGER NOT NULL,
        FOREIGN KEY (GameSettingsId) REFERENCES GameSettings_New (Id) ON DELETE CASCADE
    );");

            // 3. Helper for GUID generation (Strictly Uppercase)
            // Changed '89ab' to '89AB' to prevent lowercase variant characters
            string guidSql = "upper(hex(randomblob(4))) || '-' || upper(hex(randomblob(2))) || '-4' || substr(upper(hex(randomblob(2))),2) || '-' || substr('89AB', abs(random()) % 4 + 1, 1) || substr(upper(hex(randomblob(2))),2) || '-' || upper(hex(randomblob(6)))";

            // 4. Migrate Data using Mapping Tables
            // A. AppSettings
            migrationBuilder.Sql("CREATE TABLE _Map_App (OldId INTEGER, NewId TEXT);");
            migrationBuilder.Sql($"INSERT INTO _Map_App SELECT Id, ({guidSql}) FROM AppSettings;");
            migrationBuilder.Sql(@"INSERT INTO AppSettings_New (Id, ApplicationMode, CreatedAt, LastModifiedAt, LastSelectedView) 
        SELECT m.NewId, a.ApplicationMode, a.CreatedAt, a.LastModifiedAt, a.LastSelectedView 
        FROM AppSettings a JOIN _Map_App m ON a.Id = m.OldId;");

            // B. GameSettings
            migrationBuilder.Sql("CREATE TABLE _Map_Game (OldId INTEGER, NewId TEXT);");
            migrationBuilder.Sql($"INSERT INTO _Map_Game SELECT Id, ({guidSql}) FROM GameSettings;");
            migrationBuilder.Sql(@"INSERT INTO GameSettings_New (Id, AppSettingsId, CreatedAt, DataDirectoryPath, Discriminator, ExeDirectoryPath, Game, GameOrigin, IsAutogeneratedModPackExecuted, IsEnabled, LastModifiedAt) 
        SELECT mg.NewId, ma.NewId, g.CreatedAt, g.DataDirectoryPath, g.Discriminator, g.ExeDirectoryPath, g.Game, g.GameOrigin, g.IsAutogeneratedModPackExecuted, g.IsEnabled, g.LastModifiedAt
        FROM GameSettings g
        JOIN _Map_Game mg ON g.Id = mg.OldId
        JOIN _Map_App ma ON g.AppSettingsId = ma.OldId;");

            // C. GameStartArguments
            migrationBuilder.Sql(@"INSERT INTO GameStartArguments_New (Id, CreatedAt, DisableFrameLimit, EnableCheats, GameSettingsId, LastModifiedAt, SkipIntros) 
        SELECT (" + guidSql + @"), s.CreatedAt, s.DisableFrameLimit, s.EnableCheats, mg.NewId, s.LastModifiedAt, s.SkipIntros
        FROM GameStartArguments s
        JOIN _Map_Game mg ON s.GameSettingsId = mg.OldId;");

            // 5. Swap Tables
            migrationBuilder.Sql("DROP TABLE GameStartArguments;");
            migrationBuilder.Sql("DROP TABLE GameSettings;");
            migrationBuilder.Sql("DROP TABLE AppSettings;");
            migrationBuilder.Sql("DROP TABLE _Map_App;");
            migrationBuilder.Sql("DROP TABLE _Map_Game;");

            migrationBuilder.Sql("ALTER TABLE AppSettings_New RENAME TO AppSettings;");
            migrationBuilder.Sql("ALTER TABLE GameSettings_New RENAME TO GameSettings;");
            migrationBuilder.Sql("ALTER TABLE GameStartArguments_New RENAME TO GameStartArguments;");

            // 6. Final Indices (Re-creating the indices from the snapshot)
            migrationBuilder.Sql("CREATE INDEX IX_GameSettings_AppSettingsId ON GameSettings (AppSettingsId);");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IX_GameStartArguments_GameSettingsId ON GameStartArguments (GameSettingsId);");

            // 7. Re-enable Foreign Keys
            migrationBuilder.Sql("PRAGMA foreign_keys = ON;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new InvalidOperationException();
        }
    }
}
