//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace OF.FSimMan.Game.Fs.Fs22.SaveGame;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class careerSavegame
{

    private careerSavegameSettings settingsField;

    private careerSavegameGuidedTour guidedTourField;

    private careerSavegameMap mapField;

    private careerSavegameStatistics statisticsField;

    private careerSavegameSlotSystem slotSystemField;

    private careerSavegameMapsSplitShapeFileIds mapsSplitShapeFileIdsField;

    private careerSavegameMod[] modField;

    private byte revisionField;

    private bool validField;

    /// <remarks/>
    public careerSavegameSettings settings
    {
        get
        {
            return this.settingsField;
        }
        set
        {
            this.settingsField = value;
        }
    }

    /// <remarks/>
    public careerSavegameGuidedTour guidedTour
    {
        get
        {
            return this.guidedTourField;
        }
        set
        {
            this.guidedTourField = value;
        }
    }

    /// <remarks/>
    public careerSavegameMap map
    {
        get
        {
            return this.mapField;
        }
        set
        {
            this.mapField = value;
        }
    }

    /// <remarks/>
    public careerSavegameStatistics statistics
    {
        get
        {
            return this.statisticsField;
        }
        set
        {
            this.statisticsField = value;
        }
    }

    /// <remarks/>
    public careerSavegameSlotSystem slotSystem
    {
        get
        {
            return this.slotSystemField;
        }
        set
        {
            this.slotSystemField = value;
        }
    }

    /// <remarks/>
    public careerSavegameMapsSplitShapeFileIds mapsSplitShapeFileIds
    {
        get
        {
            return this.mapsSplitShapeFileIdsField;
        }
        set
        {
            this.mapsSplitShapeFileIdsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mod")]
    public careerSavegameMod[] mod
    {
        get
        {
            return this.modField;
        }
        set
        {
            this.modField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte revision
    {
        get
        {
            return this.revisionField;
        }
        set
        {
            this.revisionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameSettings
{

    private string savegameNameField;

    private System.DateTime creationDateField;

    private string mapIdField;

    private string mapTitleField;

    private string saveDateFormattedField;

    private System.DateTime saveDateField;

    private bool resetVehiclesField;

    private bool trafficEnabledField;

    private bool stopAndGoBrakingField;

    private bool trailerFillLimitField;

    private bool automaticMotorStartEnabledField;

    private byte growthModeField;

    private byte plannedDaysPerPeriodField;

    private bool fruitDestructionField;

    private bool plowingRequiredEnabledField;

    private bool stonesEnabledField;

    private bool weedsEnabledField;

    private bool limeRequiredField;

    private bool isSnowEnabledField;

    private byte fuelUsageField;

    private bool helperBuyFuelField;

    private bool helperBuySeedsField;

    private bool helperBuyFertilizerField;

    private byte helperSlurrySourceField;

    private byte helperManureSourceField;

    private byte densityMapRevisionField;

    private byte terrainTextureRevisionField;

    private byte terrainLodTextureRevisionField;

    private byte splitShapesRevisionField;

    private byte tipCollisionRevisionField;

    private byte placementCollisionRevisionField;

    private byte navigationCollisionRevisionField;

    private byte mapDensityMapRevisionField;

    private byte mapTerrainTextureRevisionField;

    private byte mapTerrainLodTextureRevisionField;

    private byte mapSplitShapesRevisionField;

    private byte mapTipCollisionRevisionField;

    private byte mapPlacementCollisionRevisionField;

    private byte mapNavigationCollisionRevisionField;

    private byte difficultyField;

    private byte economicDifficultyField;

    private byte dirtIntervalField;

    private decimal timeScaleField;

    private decimal autoSaveIntervalField;

    /// <remarks/>
    public string savegameName
    {
        get
        {
            return this.savegameNameField;
        }
        set
        {
            this.savegameNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime creationDate
    {
        get
        {
            return this.creationDateField;
        }
        set
        {
            this.creationDateField = value;
        }
    }

    /// <remarks/>
    public string mapId
    {
        get
        {
            return this.mapIdField;
        }
        set
        {
            this.mapIdField = value;
        }
    }

    /// <remarks/>
    public string mapTitle
    {
        get
        {
            return this.mapTitleField;
        }
        set
        {
            this.mapTitleField = value;
        }
    }

    /// <remarks/>
    public string saveDateFormatted
    {
        get
        {
            return this.saveDateFormattedField;
        }
        set
        {
            this.saveDateFormattedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime saveDate
    {
        get
        {
            return this.saveDateField;
        }
        set
        {
            this.saveDateField = value;
        }
    }

    /// <remarks/>
    public bool resetVehicles
    {
        get
        {
            return this.resetVehiclesField;
        }
        set
        {
            this.resetVehiclesField = value;
        }
    }

    /// <remarks/>
    public bool trafficEnabled
    {
        get
        {
            return this.trafficEnabledField;
        }
        set
        {
            this.trafficEnabledField = value;
        }
    }

    /// <remarks/>
    public bool stopAndGoBraking
    {
        get
        {
            return this.stopAndGoBrakingField;
        }
        set
        {
            this.stopAndGoBrakingField = value;
        }
    }

    /// <remarks/>
    public bool trailerFillLimit
    {
        get
        {
            return this.trailerFillLimitField;
        }
        set
        {
            this.trailerFillLimitField = value;
        }
    }

    /// <remarks/>
    public bool automaticMotorStartEnabled
    {
        get
        {
            return this.automaticMotorStartEnabledField;
        }
        set
        {
            this.automaticMotorStartEnabledField = value;
        }
    }

    /// <remarks/>
    public byte growthMode
    {
        get
        {
            return this.growthModeField;
        }
        set
        {
            this.growthModeField = value;
        }
    }

    /// <remarks/>
    public byte plannedDaysPerPeriod
    {
        get
        {
            return this.plannedDaysPerPeriodField;
        }
        set
        {
            this.plannedDaysPerPeriodField = value;
        }
    }

    /// <remarks/>
    public bool fruitDestruction
    {
        get
        {
            return this.fruitDestructionField;
        }
        set
        {
            this.fruitDestructionField = value;
        }
    }

    /// <remarks/>
    public bool plowingRequiredEnabled
    {
        get
        {
            return this.plowingRequiredEnabledField;
        }
        set
        {
            this.plowingRequiredEnabledField = value;
        }
    }

    /// <remarks/>
    public bool stonesEnabled
    {
        get
        {
            return this.stonesEnabledField;
        }
        set
        {
            this.stonesEnabledField = value;
        }
    }

    /// <remarks/>
    public bool weedsEnabled
    {
        get
        {
            return this.weedsEnabledField;
        }
        set
        {
            this.weedsEnabledField = value;
        }
    }

    /// <remarks/>
    public bool limeRequired
    {
        get
        {
            return this.limeRequiredField;
        }
        set
        {
            this.limeRequiredField = value;
        }
    }

    /// <remarks/>
    public bool isSnowEnabled
    {
        get
        {
            return this.isSnowEnabledField;
        }
        set
        {
            this.isSnowEnabledField = value;
        }
    }

    /// <remarks/>
    public byte fuelUsage
    {
        get
        {
            return this.fuelUsageField;
        }
        set
        {
            this.fuelUsageField = value;
        }
    }

    /// <remarks/>
    public bool helperBuyFuel
    {
        get
        {
            return this.helperBuyFuelField;
        }
        set
        {
            this.helperBuyFuelField = value;
        }
    }

    /// <remarks/>
    public bool helperBuySeeds
    {
        get
        {
            return this.helperBuySeedsField;
        }
        set
        {
            this.helperBuySeedsField = value;
        }
    }

    /// <remarks/>
    public bool helperBuyFertilizer
    {
        get
        {
            return this.helperBuyFertilizerField;
        }
        set
        {
            this.helperBuyFertilizerField = value;
        }
    }

    /// <remarks/>
    public byte helperSlurrySource
    {
        get
        {
            return this.helperSlurrySourceField;
        }
        set
        {
            this.helperSlurrySourceField = value;
        }
    }

    /// <remarks/>
    public byte helperManureSource
    {
        get
        {
            return this.helperManureSourceField;
        }
        set
        {
            this.helperManureSourceField = value;
        }
    }

    /// <remarks/>
    public byte densityMapRevision
    {
        get
        {
            return this.densityMapRevisionField;
        }
        set
        {
            this.densityMapRevisionField = value;
        }
    }

    /// <remarks/>
    public byte terrainTextureRevision
    {
        get
        {
            return this.terrainTextureRevisionField;
        }
        set
        {
            this.terrainTextureRevisionField = value;
        }
    }

    /// <remarks/>
    public byte terrainLodTextureRevision
    {
        get
        {
            return this.terrainLodTextureRevisionField;
        }
        set
        {
            this.terrainLodTextureRevisionField = value;
        }
    }

    /// <remarks/>
    public byte splitShapesRevision
    {
        get
        {
            return this.splitShapesRevisionField;
        }
        set
        {
            this.splitShapesRevisionField = value;
        }
    }

    /// <remarks/>
    public byte tipCollisionRevision
    {
        get
        {
            return this.tipCollisionRevisionField;
        }
        set
        {
            this.tipCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte placementCollisionRevision
    {
        get
        {
            return this.placementCollisionRevisionField;
        }
        set
        {
            this.placementCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte navigationCollisionRevision
    {
        get
        {
            return this.navigationCollisionRevisionField;
        }
        set
        {
            this.navigationCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapDensityMapRevision
    {
        get
        {
            return this.mapDensityMapRevisionField;
        }
        set
        {
            this.mapDensityMapRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapTerrainTextureRevision
    {
        get
        {
            return this.mapTerrainTextureRevisionField;
        }
        set
        {
            this.mapTerrainTextureRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapTerrainLodTextureRevision
    {
        get
        {
            return this.mapTerrainLodTextureRevisionField;
        }
        set
        {
            this.mapTerrainLodTextureRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapSplitShapesRevision
    {
        get
        {
            return this.mapSplitShapesRevisionField;
        }
        set
        {
            this.mapSplitShapesRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapTipCollisionRevision
    {
        get
        {
            return this.mapTipCollisionRevisionField;
        }
        set
        {
            this.mapTipCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapPlacementCollisionRevision
    {
        get
        {
            return this.mapPlacementCollisionRevisionField;
        }
        set
        {
            this.mapPlacementCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte mapNavigationCollisionRevision
    {
        get
        {
            return this.mapNavigationCollisionRevisionField;
        }
        set
        {
            this.mapNavigationCollisionRevisionField = value;
        }
    }

    /// <remarks/>
    public byte difficulty
    {
        get
        {
            return this.difficultyField;
        }
        set
        {
            this.difficultyField = value;
        }
    }

    /// <remarks/>
    public byte economicDifficulty
    {
        get
        {
            return this.economicDifficultyField;
        }
        set
        {
            this.economicDifficultyField = value;
        }
    }

    /// <remarks/>
    public byte dirtInterval
    {
        get
        {
            return this.dirtIntervalField;
        }
        set
        {
            this.dirtIntervalField = value;
        }
    }

    /// <remarks/>
    public decimal timeScale
    {
        get
        {
            return this.timeScaleField;
        }
        set
        {
            this.timeScaleField = value;
        }
    }

    /// <remarks/>
    public decimal autoSaveInterval
    {
        get
        {
            return this.autoSaveIntervalField;
        }
        set
        {
            this.autoSaveIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameGuidedTour
{

    private bool activeField;

    private byte currentStepIndexField;

    private string stateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte currentStepIndex
    {
        get
        {
            return this.currentStepIndexField;
        }
        set
        {
            this.currentStepIndexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameMap
{

    private byte foundHelpIconsField;

    /// <remarks/>
    public byte foundHelpIcons
    {
        get
        {
            return this.foundHelpIconsField;
        }
        set
        {
            this.foundHelpIconsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameStatistics
{

    private uint moneyField;

    private decimal playTimeField;

    /// <remarks/>
    public uint money
    {
        get
        {
            return this.moneyField;
        }
        set
        {
            this.moneyField = value;
        }
    }

    /// <remarks/>
    public decimal playTime
    {
        get
        {
            return this.playTimeField;
        }
        set
        {
            this.playTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameSlotSystem
{

    private ushort slotUsageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort slotUsage
    {
        get
        {
            return this.slotUsageField;
        }
        set
        {
            this.slotUsageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameMapsSplitShapeFileIds
{

    private careerSavegameMapsSplitShapeFileIdsID idField;

    private byte countField;

    /// <remarks/>
    public careerSavegameMapsSplitShapeFileIdsID id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameMapsSplitShapeFileIdsID
{

    private byte idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class careerSavegameMod
{

    private string modNameField;

    private string titleField;

    private string versionField;

    private bool requiredField;

    private string fileHashField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modName
    {
        get
        {
            return this.modNameField;
        }
        set
        {
            this.modNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool required
    {
        get
        {
            return this.requiredField;
        }
        set
        {
            this.requiredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileHash
    {
        get
        {
            return this.fileHashField;
        }
        set
        {
            this.fileHashField = value;
        }
    }
}