//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace OF.FSimMan.Game.Fs.Fs22.Mod;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class modDesc
{

    private modDescTitle titleField;

    private string versionField;

    private string authorField;

    private modDescDescription descriptionField;

    private modDescMultiplayer multiplayerField;

    private string iconFilenameField;

    private byte descVersionField;

    /// <remarks/>
    public modDescTitle title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    public string author
    {
        get
        {
            return this.authorField;
        }
        set
        {
            this.authorField = value;
        }
    }

    /// <remarks/>
    public modDescDescription description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public modDescMultiplayer multiplayer
    {
        get
        {
            return this.multiplayerField;
        }
        set
        {
            this.multiplayerField = value;
        }
    }

    /// <remarks/>
    public string iconFilename
    {
        get
        {
            return this.iconFilenameField;
        }
        set
        {
            this.iconFilenameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte descVersion
    {
        get
        {
            return this.descVersionField;
        }
        set
        {
            this.descVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class modDescTitle
{

    private string enField;

    private string deField;

    /// <remarks/>
    public string en
    {
        get
        {
            return this.enField;
        }
        set
        {
            this.enField = value;
        }
    }

    /// <remarks/>
    public string de
    {
        get
        {
            return this.deField;
        }
        set
        {
            this.deField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class modDescDescription
{

    private string enField;

    private string deField;

    /// <remarks/>
    public string en
    {
        get
        {
            return this.enField;
        }
        set
        {
            this.enField = value;
        }
    }

    /// <remarks/>
    public string de
    {
        get
        {
            return this.deField;
        }
        set
        {
            this.deField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class modDescMultiplayer
{

    private bool supportedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool supported
    {
        get
        {
            return this.supportedField;
        }
        set
        {
            this.supportedField = value;
        }
    }
}
