//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OF.Base.Objects;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace OF.FSimMan.Game.Fs.Fs25;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class gameSettings : IGameSettings {
    
    private gameSettingsModsDirectoryOverride modsDirectoryOverrideField;
    
    private ushort defaultMultiplayerPortField;
    
    private ushort motorStopTimerDurationField;
    
    private ushort horseAbandonTimerDurationField;
    
    private bool invertYLookField;
    
    private bool isHeadTrackingEnabledField;
    
    private decimal forceFeedbackField;
    
    private bool isGamepadEnabledField;
    
    private decimal cameraSensitivityField;
    
    private decimal vehicleArmSensitivityField;
    
    private decimal realBeaconLightBrightnessField;
    
    private decimal steeringBackSpeedField;
    
    private decimal steeringSensitivityField;
    
    private ushort inputHelpModeField;
    
    private bool easyArmControlField;
    
    private bool gyroscopeSteeringField;
    
    private bool hintsField;
    
    private bool cameraTiltingField;
    
    private ushort frameLimitField;
    
    private bool showAllModsField;
    
    private string onlinePresenceNameField;
    
    private gameSettingsPlayer playerField;
    
    private ushort mpLanguageField;
    
    private gameSettingsVolume volumeField;
    
    private gameSettingsSoundPlayer soundPlayerField;
    
    private bool radioIsActiveField;
    
    private bool radioVehicleOnlyField;
    
    private gameSettingsVoice voiceField;
    
    private gameSettingsUnits unitsField;
    
    private bool isTrainTabbableField;
    
    private bool showTriggerMarkerField;
    
    private bool showHelpTriggerField;
    
    private bool showFieldInfoField;
    
    private bool showHelpIconsField;
    
    private bool showHelpMenuField;
    
    private bool resetCameraField;
    
    private bool activeSuspensionCameraField;
    
    private bool cameraCheckCollisionField;
    
    private bool useWorldCameraField;
    
    private string ingameMapStateField;
    
    private ushort ingameMapFiltersField;
    
    private ushort directionChangeModeField;
    
    private ushort gearShiftModeField;
    
    private ushort hudSpeedGaugeField;
    
    private bool woodHarvesterAutoCutField;
    
    private bool shownFreemodeWarningField;
    
    private bool showMultiplayerNamesField;
    
    private uint ingameMapGrowthFilterField;
    
    private uint ingameMapSoilFilterField;
    
    private uint ingameMapHotspotFilterField;
    
    private object ingameMapFruitFilterField;
    
    private bool useColorblindModeField;
    
    private ushort maxNumMirrorsField;
    
    private ushort lightsProfileField;
    
    private gameSettingsFovY fovYField;
    
    private decimal uiScaleField;
    
    private bool realBeaconLightsField;
    
    private bool cameraBobbingField;
    
    private bool steeringAssistLinesField;
    
    private gameSettingsLastPlayerStyle lastPlayerStyleField;
    
    private gameSettingsLastCreatedLicensePlate lastCreatedLicensePlateField;
    
    private gameSettingsJoinGame joinGameField;
    
    private ushort revisionField;
    
    /// <remarks/>
    public gameSettingsModsDirectoryOverride modsDirectoryOverride {
        get {
            return this.modsDirectoryOverrideField;
        }
        set {
            this.modsDirectoryOverrideField = value;
        }
    }
    
    /// <remarks/>
    public ushort defaultMultiplayerPort {
        get {
            return this.defaultMultiplayerPortField;
        }
        set {
            this.defaultMultiplayerPortField = value;
        }
    }
    
    /// <remarks/>
    public ushort motorStopTimerDuration {
        get {
            return this.motorStopTimerDurationField;
        }
        set {
            this.motorStopTimerDurationField = value;
        }
    }
    
    /// <remarks/>
    public ushort horseAbandonTimerDuration {
        get {
            return this.horseAbandonTimerDurationField;
        }
        set {
            this.horseAbandonTimerDurationField = value;
        }
    }
    
    /// <remarks/>
    public bool invertYLook {
        get {
            return this.invertYLookField;
        }
        set {
            this.invertYLookField = value;
        }
    }
    
    /// <remarks/>
    public bool isHeadTrackingEnabled {
        get {
            return this.isHeadTrackingEnabledField;
        }
        set {
            this.isHeadTrackingEnabledField = value;
        }
    }
    
    /// <remarks/>
    public decimal forceFeedback {
        get {
            return this.forceFeedbackField;
        }
        set {
            this.forceFeedbackField = value;
        }
    }
    
    /// <remarks/>
    public bool isGamepadEnabled {
        get {
            return this.isGamepadEnabledField;
        }
        set {
            this.isGamepadEnabledField = value;
        }
    }
    
    /// <remarks/>
    public decimal cameraSensitivity {
        get {
            return this.cameraSensitivityField;
        }
        set {
            this.cameraSensitivityField = value;
        }
    }
    
    /// <remarks/>
    public decimal vehicleArmSensitivity {
        get {
            return this.vehicleArmSensitivityField;
        }
        set {
            this.vehicleArmSensitivityField = value;
        }
    }
    
    /// <remarks/>
    public decimal realBeaconLightBrightness {
        get {
            return this.realBeaconLightBrightnessField;
        }
        set {
            this.realBeaconLightBrightnessField = value;
        }
    }
    
    /// <remarks/>
    public decimal steeringBackSpeed {
        get {
            return this.steeringBackSpeedField;
        }
        set {
            this.steeringBackSpeedField = value;
        }
    }
    
    /// <remarks/>
    public decimal steeringSensitivity {
        get {
            return this.steeringSensitivityField;
        }
        set {
            this.steeringSensitivityField = value;
        }
    }
    
    /// <remarks/>
    public ushort inputHelpMode {
        get {
            return this.inputHelpModeField;
        }
        set {
            this.inputHelpModeField = value;
        }
    }
    
    /// <remarks/>
    public bool easyArmControl {
        get {
            return this.easyArmControlField;
        }
        set {
            this.easyArmControlField = value;
        }
    }
    
    /// <remarks/>
    public bool gyroscopeSteering {
        get {
            return this.gyroscopeSteeringField;
        }
        set {
            this.gyroscopeSteeringField = value;
        }
    }
    
    /// <remarks/>
    public bool hints {
        get {
            return this.hintsField;
        }
        set {
            this.hintsField = value;
        }
    }
    
    /// <remarks/>
    public bool cameraTilting {
        get {
            return this.cameraTiltingField;
        }
        set {
            this.cameraTiltingField = value;
        }
    }
    
    /// <remarks/>
    public ushort frameLimit {
        get {
            return this.frameLimitField;
        }
        set {
            this.frameLimitField = value;
        }
    }
    
    /// <remarks/>
    public bool showAllMods {
        get {
            return this.showAllModsField;
        }
        set {
            this.showAllModsField = value;
        }
    }
    
    /// <remarks/>
    public string onlinePresenceName {
        get {
            return this.onlinePresenceNameField;
        }
        set {
            this.onlinePresenceNameField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsPlayer player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    public ushort mpLanguage {
        get {
            return this.mpLanguageField;
        }
        set {
            this.mpLanguageField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsVolume volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsSoundPlayer soundPlayer {
        get {
            return this.soundPlayerField;
        }
        set {
            this.soundPlayerField = value;
        }
    }
    
    /// <remarks/>
    public bool radioIsActive {
        get {
            return this.radioIsActiveField;
        }
        set {
            this.radioIsActiveField = value;
        }
    }
    
    /// <remarks/>
    public bool radioVehicleOnly {
        get {
            return this.radioVehicleOnlyField;
        }
        set {
            this.radioVehicleOnlyField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsVoice voice {
        get {
            return this.voiceField;
        }
        set {
            this.voiceField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsUnits units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public bool isTrainTabbable {
        get {
            return this.isTrainTabbableField;
        }
        set {
            this.isTrainTabbableField = value;
        }
    }
    
    /// <remarks/>
    public bool showTriggerMarker {
        get {
            return this.showTriggerMarkerField;
        }
        set {
            this.showTriggerMarkerField = value;
        }
    }
    
    /// <remarks/>
    public bool showHelpTrigger {
        get {
            return this.showHelpTriggerField;
        }
        set {
            this.showHelpTriggerField = value;
        }
    }
    
    /// <remarks/>
    public bool showFieldInfo {
        get {
            return this.showFieldInfoField;
        }
        set {
            this.showFieldInfoField = value;
        }
    }
    
    /// <remarks/>
    public bool showHelpIcons {
        get {
            return this.showHelpIconsField;
        }
        set {
            this.showHelpIconsField = value;
        }
    }
    
    /// <remarks/>
    public bool showHelpMenu {
        get {
            return this.showHelpMenuField;
        }
        set {
            this.showHelpMenuField = value;
        }
    }
    
    /// <remarks/>
    public bool resetCamera {
        get {
            return this.resetCameraField;
        }
        set {
            this.resetCameraField = value;
        }
    }
    
    /// <remarks/>
    public bool activeSuspensionCamera {
        get {
            return this.activeSuspensionCameraField;
        }
        set {
            this.activeSuspensionCameraField = value;
        }
    }
    
    /// <remarks/>
    public bool cameraCheckCollision {
        get {
            return this.cameraCheckCollisionField;
        }
        set {
            this.cameraCheckCollisionField = value;
        }
    }
    
    /// <remarks/>
    public bool useWorldCamera {
        get {
            return this.useWorldCameraField;
        }
        set {
            this.useWorldCameraField = value;
        }
    }
    
    /// <remarks/>
    public string ingameMapState {
        get {
            return this.ingameMapStateField;
        }
        set {
            this.ingameMapStateField = value;
        }
    }
    
    /// <remarks/>
    public ushort ingameMapFilters {
        get {
            return this.ingameMapFiltersField;
        }
        set {
            this.ingameMapFiltersField = value;
        }
    }
    
    /// <remarks/>
    public ushort directionChangeMode {
        get {
            return this.directionChangeModeField;
        }
        set {
            this.directionChangeModeField = value;
        }
    }
    
    /// <remarks/>
    public ushort gearShiftMode {
        get {
            return this.gearShiftModeField;
        }
        set {
            this.gearShiftModeField = value;
        }
    }
    
    /// <remarks/>
    public ushort hudSpeedGauge {
        get {
            return this.hudSpeedGaugeField;
        }
        set {
            this.hudSpeedGaugeField = value;
        }
    }
    
    /// <remarks/>
    public bool woodHarvesterAutoCut {
        get {
            return this.woodHarvesterAutoCutField;
        }
        set {
            this.woodHarvesterAutoCutField = value;
        }
    }
    
    /// <remarks/>
    public bool shownFreemodeWarning {
        get {
            return this.shownFreemodeWarningField;
        }
        set {
            this.shownFreemodeWarningField = value;
        }
    }
    
    /// <remarks/>
    public bool showMultiplayerNames {
        get {
            return this.showMultiplayerNamesField;
        }
        set {
            this.showMultiplayerNamesField = value;
        }
    }
    
    /// <remarks/>
    public uint ingameMapGrowthFilter {
        get {
            return this.ingameMapGrowthFilterField;
        }
        set {
            this.ingameMapGrowthFilterField = value;
        }
    }
    
    /// <remarks/>
    public uint ingameMapSoilFilter {
        get {
            return this.ingameMapSoilFilterField;
        }
        set {
            this.ingameMapSoilFilterField = value;
        }
    }
    
    /// <remarks/>
    public uint ingameMapHotspotFilter {
        get {
            return this.ingameMapHotspotFilterField;
        }
        set {
            this.ingameMapHotspotFilterField = value;
        }
    }
    
    /// <remarks/>
    public object ingameMapFruitFilter {
        get {
            return this.ingameMapFruitFilterField;
        }
        set {
            this.ingameMapFruitFilterField = value;
        }
    }
    
    /// <remarks/>
    public bool useColorblindMode {
        get {
            return this.useColorblindModeField;
        }
        set {
            this.useColorblindModeField = value;
        }
    }
    
    /// <remarks/>
    public ushort maxNumMirrors {
        get {
            return this.maxNumMirrorsField;
        }
        set {
            this.maxNumMirrorsField = value;
        }
    }
    
    /// <remarks/>
    public ushort lightsProfile {
        get {
            return this.lightsProfileField;
        }
        set {
            this.lightsProfileField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsFovY fovY {
        get {
            return this.fovYField;
        }
        set {
            this.fovYField = value;
        }
    }
    
    /// <remarks/>
    public decimal uiScale {
        get {
            return this.uiScaleField;
        }
        set {
            this.uiScaleField = value;
        }
    }
    
    /// <remarks/>
    public bool realBeaconLights {
        get {
            return this.realBeaconLightsField;
        }
        set {
            this.realBeaconLightsField = value;
        }
    }
    
    /// <remarks/>
    public bool cameraBobbing {
        get {
            return this.cameraBobbingField;
        }
        set {
            this.cameraBobbingField = value;
        }
    }
    
    /// <remarks/>
    public bool steeringAssistLines {
        get {
            return this.steeringAssistLinesField;
        }
        set {
            this.steeringAssistLinesField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyle lastPlayerStyle {
        get {
            return this.lastPlayerStyleField;
        }
        set {
            this.lastPlayerStyleField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastCreatedLicensePlate lastCreatedLicensePlate {
        get {
            return this.lastCreatedLicensePlateField;
        }
        set {
            this.lastCreatedLicensePlateField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsJoinGame joinGame {
        get {
            return this.joinGameField;
        }
        set {
            this.joinGameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsModsDirectoryOverride {
    
    private bool activeField;
    
    private string directoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directory {
        get {
            return this.directoryField;
        }
        set {
            this.directoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsPlayer {
    
    private bool lastPlayerStyleMaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool lastPlayerStyleMale {
        get {
            return this.lastPlayerStyleMaleField;
        }
        set {
            this.lastPlayerStyleMaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsVolume {
    
    private decimal musicField;
    
    private decimal vehicleField;
    
    private decimal environmentField;
    
    private decimal characterField;
    
    private decimal radioField;
    
    private decimal guiField;
    
    private decimal noFocusField;
    
    private decimal voiceField;
    
    private decimal voiceInputField;
    
    /// <remarks/>
    public decimal music {
        get {
            return this.musicField;
        }
        set {
            this.musicField = value;
        }
    }
    
    /// <remarks/>
    public decimal vehicle {
        get {
            return this.vehicleField;
        }
        set {
            this.vehicleField = value;
        }
    }
    
    /// <remarks/>
    public decimal environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    public decimal character {
        get {
            return this.characterField;
        }
        set {
            this.characterField = value;
        }
    }
    
    /// <remarks/>
    public decimal radio {
        get {
            return this.radioField;
        }
        set {
            this.radioField = value;
        }
    }
    
    /// <remarks/>
    public decimal gui {
        get {
            return this.guiField;
        }
        set {
            this.guiField = value;
        }
    }
    
    /// <remarks/>
    public decimal noFocus {
        get {
            return this.noFocusField;
        }
        set {
            this.noFocusField = value;
        }
    }
    
    /// <remarks/>
    public decimal voice {
        get {
            return this.voiceField;
        }
        set {
            this.voiceField = value;
        }
    }
    
    /// <remarks/>
    public decimal voiceInput {
        get {
            return this.voiceInputField;
        }
        set {
            this.voiceInputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsSoundPlayer {
    
    private bool allowStreamsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool allowStreams {
        get {
            return this.allowStreamsField;
        }
        set {
            this.allowStreamsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsVoice {
    
    private ushort modeField;
    
    private ushort inputSensitivityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort inputSensitivity {
        get {
            return this.inputSensitivityField;
        }
        set {
            this.inputSensitivityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsUnits {
    
    private ushort moneyField;
    
    private bool milesField;
    
    private bool fahrenheitField;
    
    private bool acreField;
    
    /// <remarks/>
    public ushort money {
        get {
            return this.moneyField;
        }
        set {
            this.moneyField = value;
        }
    }
    
    /// <remarks/>
    public bool miles {
        get {
            return this.milesField;
        }
        set {
            this.milesField = value;
        }
    }
    
    /// <remarks/>
    public bool fahrenheit {
        get {
            return this.fahrenheitField;
        }
        set {
            this.fahrenheitField = value;
        }
    }
    
    /// <remarks/>
    public bool acre {
        get {
            return this.acreField;
        }
        set {
            this.acreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsFovY {
    
    private decimal playerFirstPersonField;
    
    private decimal playerThirdPersonField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal playerFirstPerson {
        get {
            return this.playerFirstPersonField;
        }
        set {
            this.playerFirstPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal playerThirdPerson {
        get {
            return this.playerThirdPersonField;
        }
        set {
            this.playerThirdPersonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyle {
    
    private gameSettingsLastPlayerStyleFacegear facegearField;
    
    private gameSettingsLastPlayerStyleOnepiece onepieceField;
    
    private gameSettingsLastPlayerStyleBottom bottomField;
    
    private gameSettingsLastPlayerStyleFace faceField;
    
    private gameSettingsLastPlayerStyleTop topField;
    
    private gameSettingsLastPlayerStyleGloves glovesField;
    
    private gameSettingsLastPlayerStyleHeadgear headgearField;
    
    private gameSettingsLastPlayerStyleGlasses glassesField;
    
    private gameSettingsLastPlayerStyleFootwear footwearField;
    
    private gameSettingsLastPlayerStyleHairStyle hairStyleField;
    
    private gameSettingsLastPlayerStyleBeard beardField;
    
    private string filenameField;
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleFacegear facegear {
        get {
            return this.facegearField;
        }
        set {
            this.facegearField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleOnepiece onepiece {
        get {
            return this.onepieceField;
        }
        set {
            this.onepieceField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleBottom bottom {
        get {
            return this.bottomField;
        }
        set {
            this.bottomField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleFace face {
        get {
            return this.faceField;
        }
        set {
            this.faceField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleTop top {
        get {
            return this.topField;
        }
        set {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleGloves gloves {
        get {
            return this.glovesField;
        }
        set {
            this.glovesField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleHeadgear headgear {
        get {
            return this.headgearField;
        }
        set {
            this.headgearField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleGlasses glasses {
        get {
            return this.glassesField;
        }
        set {
            this.glassesField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleFootwear footwear {
        get {
            return this.footwearField;
        }
        set {
            this.footwearField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleHairStyle hairStyle {
        get {
            return this.hairStyleField;
        }
        set {
            this.hairStyleField = value;
        }
    }
    
    /// <remarks/>
    public gameSettingsLastPlayerStyleBeard beard {
        get {
            return this.beardField;
        }
        set {
            this.beardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleFacegear {
    
    private ushort colorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleOnepiece {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleBottom {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleFace {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleTop {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleGloves {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleHeadgear {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleGlasses {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleFootwear {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleHairStyle {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastPlayerStyleBeard {
    
    private ushort colorField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsLastCreatedLicensePlate {
    
    private ushort variationField;
    
    private ushort colorField;
    
    private ushort placementField;
    
    private string charactersField;
    
    private string configurationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort variation {
        get {
            return this.variationField;
        }
        set {
            this.variationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort placement {
        get {
            return this.placementField;
        }
        set {
            this.placementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string characters {
        get {
            return this.charactersField;
        }
        set {
            this.charactersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string configuration {
        get {
            return this.configurationField;
        }
        set {
            this.configurationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSettingsJoinGame {
    
    private bool includePasswordProtectedField;
    
    private bool includeFullGamesField;
    
    private bool onlyWithAllModsAvailableField;
    
    private string serverNameField;
    
    private string mapIdField;
    
    private ushort languageField;
    
    private ushort capacityField;
    
    private bool allowCrossPlayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool includePasswordProtected {
        get {
            return this.includePasswordProtectedField;
        }
        set {
            this.includePasswordProtectedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool includeFullGames {
        get {
            return this.includeFullGamesField;
        }
        set {
            this.includeFullGamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool onlyWithAllModsAvailable {
        get {
            return this.onlyWithAllModsAvailableField;
        }
        set {
            this.onlyWithAllModsAvailableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serverName {
        get {
            return this.serverNameField;
        }
        set {
            this.serverNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mapId {
        get {
            return this.mapIdField;
        }
        set {
            this.mapIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort capacity {
        get {
            return this.capacityField;
        }
        set {
            this.capacityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool allowCrossPlay {
        get {
            return this.allowCrossPlayField;
        }
        set {
            this.allowCrossPlayField = value;
        }
    }
}
