using OF.Base.Objects;
using System.Xml.Serialization;

namespace OF.FSimMan.Management.Games
{
    public abstract class AppSettingsGameDataBase : DataObject
    {
        protected AppSettingsGameDataBase() { }
    }

    public abstract class AppSettingsGameDataBase<T> : AppSettingsGameDataBase, IDataObject<T> where T : AppSettingsGameBase
    {
        [XmlElement(IsNullable = false)]
        public Game Game = Game.None; // OFDOI: Cannot be none. Must be replaced for migration

        [XmlElement(IsNullable = false)]
        public bool IsEnabled = false;

        [XmlElement(IsNullable = false)]
        public bool IsAutogeneratedModPackExecuted = false;

        [XmlElement(IsNullable = false)]
        public string ExeDirectoryPath = string.Empty;

        public virtual T FromData()
        {
            T temp = Activator.CreateInstance<T>();
            temp._game = Game;
            temp.IsEnabled = IsEnabled;
            temp.IsAutogeneratedModPackExecuted = IsAutogeneratedModPackExecuted;
            temp.ExeDirectoryPath = ExeDirectoryPath;
            return temp;
        }

        public virtual void ToData(T value)
        {
            Game = value._game;
            IsEnabled = value.IsEnabled;
            IsAutogeneratedModPackExecuted = value.IsAutogeneratedModPackExecuted;
            ExeDirectoryPath = value.ExeDirectoryPath;
        }
    }
}
