using OF.Base.Objects;
using OF.FSimMan.Management.Games.Fs;
using System.Xml.Serialization;

namespace OF.FSimMan.Management.Games
{
    public abstract class AppSettingsGameDataBase : DataObject
    {
        protected AppSettingsGameDataBase() { }
    }

    public abstract class AppSettingsGameDataBase<T> : AppSettingsGameDataBase, IDataObject<T> where T : AppSettingsGameBase
    {
        [XmlElement(IsNullable = false)]
        public Game Game = Game.None;

        [XmlElement(IsNullable = false)]
        public bool IsEnabled = false;

        [XmlElement(IsNullable = false)]
        public bool IsAutogeneratedModPackExecuted = false;

        [XmlElement(IsNullable = false)]
        public string ExeDirectoryPath = string.Empty;

        public virtual T FromData()
        {
            if (Game.Equals(Game.None)) MigrateGame();

            T temp = Activator.CreateInstance<T>();
            temp._game = Game;
            temp.IsEnabled = IsEnabled;
            temp.IsAutogeneratedModPackExecuted = IsAutogeneratedModPackExecuted;
            temp.ExeDirectoryPath = ExeDirectoryPath;
            return temp;
        }

        public virtual void ToData(T value)
        {
            Game = value._game;
            IsEnabled = value.IsEnabled;
            IsAutogeneratedModPackExecuted = value.IsAutogeneratedModPackExecuted;
            ExeDirectoryPath = value.ExeDirectoryPath;
        }

        private void MigrateGame()
        {
            IsAutogeneratedModPackExecuted = true;

            if (typeof(T).IsAssignableTo(typeof(AppSettingsGameFs22)))
            {
                Game = Game.FarmingSim22;
                return;
            }
            if (typeof(T).IsAssignableTo(typeof(AppSettingsGameFs25)))
            {
                Game = Game.FarmingSim25;
                return;
            }
        }
    }
}
