//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


namespace OliverFida.FSimMan.FS22
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class gameSettings
    {

        private gameSettingsModsDirectoryOverride modsDirectoryOverrideField;

        private ushort defaultMultiplayerPortField;

        private byte motorStopTimerDurationField;

        private ushort horseAbandonTimerDurationField;

        private bool invertYLookField;

        private bool isHeadTrackingEnabledField;

        private decimal forceFeedbackField;

        private bool isGamepadEnabledField;

        private decimal cameraSensitivityField;

        private decimal vehicleArmSensitivityField;

        private decimal realBeaconLightBrightnessField;

        private decimal steeringBackSpeedField;

        private decimal steeringSensitivityField;

        private byte inputHelpModeField;

        private bool easyArmControlField;

        private bool gyroscopeSteeringField;

        private bool hintsField;

        private bool cameraTiltingField;

        private byte frameLimitField;

        private bool showAllModsField;

        private string onlinePresenceNameField;

        private gameSettingsPlayer playerField;

        private byte mpLanguageField;

        private gameSettingsVolume volumeField;

        private gameSettingsSoundPlayer soundPlayerField;

        private bool radioIsActiveField;

        private bool radioVehicleOnlyField;

        private gameSettingsVoice voiceField;

        private gameSettingsUnits unitsField;

        private bool isTrainTabbableField;

        private bool showTriggerMarkerField;

        private bool showHelpTriggerField;

        private bool showFieldInfoField;

        private bool showHelpIconsField;

        private bool showHelpMenuField;

        private bool resetCameraField;

        private bool activeSuspensionCameraField;

        private bool cameraCheckCollisionField;

        private bool useWorldCameraField;

        private byte ingameMapStateField;

        private byte ingameMapFiltersField;

        private byte directionChangeModeField;

        private byte gearShiftModeField;

        private byte hudSpeedGaugeField;

        private bool woodHarvesterAutoCutField;

        private bool shownFreemodeWarningField;

        private bool showMultiplayerNamesField;

        private ushort ingameMapGrowthFilterField;

        private byte ingameMapSoilFilterField;

        private object ingameMapFruitFilterField;

        private bool useColorblindModeField;

        private byte maxNumMirrorsField;

        private byte lightsProfileField;

        private decimal fovYField;

        private decimal uiScaleField;

        private bool realBeaconLightsField;

        private bool cameraBobbingField;

        private gameSettingsPrecisionFarming precisionFarmingField;

        private gameSettingsLastPlayerStyle lastPlayerStyleField;

        private gameSettingsLastCreatedLicensePlate lastCreatedLicensePlateField;

        private object joinGameField;

        private gameSettingsCreateGame createGameField;

        private byte revisionField;

        /// <remarks/>
        public gameSettingsModsDirectoryOverride modsDirectoryOverride
        {
            get
            {
                return this.modsDirectoryOverrideField;
            }
            set
            {
                this.modsDirectoryOverrideField = value;
            }
        }

        /// <remarks/>
        public ushort defaultMultiplayerPort
        {
            get
            {
                return this.defaultMultiplayerPortField;
            }
            set
            {
                this.defaultMultiplayerPortField = value;
            }
        }

        /// <remarks/>
        public byte motorStopTimerDuration
        {
            get
            {
                return this.motorStopTimerDurationField;
            }
            set
            {
                this.motorStopTimerDurationField = value;
            }
        }

        /// <remarks/>
        public ushort horseAbandonTimerDuration
        {
            get
            {
                return this.horseAbandonTimerDurationField;
            }
            set
            {
                this.horseAbandonTimerDurationField = value;
            }
        }

        /// <remarks/>
        public bool invertYLook
        {
            get
            {
                return this.invertYLookField;
            }
            set
            {
                this.invertYLookField = value;
            }
        }

        /// <remarks/>
        public bool isHeadTrackingEnabled
        {
            get
            {
                return this.isHeadTrackingEnabledField;
            }
            set
            {
                this.isHeadTrackingEnabledField = value;
            }
        }

        /// <remarks/>
        public decimal forceFeedback
        {
            get
            {
                return this.forceFeedbackField;
            }
            set
            {
                this.forceFeedbackField = value;
            }
        }

        /// <remarks/>
        public bool isGamepadEnabled
        {
            get
            {
                return this.isGamepadEnabledField;
            }
            set
            {
                this.isGamepadEnabledField = value;
            }
        }

        /// <remarks/>
        public decimal cameraSensitivity
        {
            get
            {
                return this.cameraSensitivityField;
            }
            set
            {
                this.cameraSensitivityField = value;
            }
        }

        /// <remarks/>
        public decimal vehicleArmSensitivity
        {
            get
            {
                return this.vehicleArmSensitivityField;
            }
            set
            {
                this.vehicleArmSensitivityField = value;
            }
        }

        /// <remarks/>
        public decimal realBeaconLightBrightness
        {
            get
            {
                return this.realBeaconLightBrightnessField;
            }
            set
            {
                this.realBeaconLightBrightnessField = value;
            }
        }

        /// <remarks/>
        public decimal steeringBackSpeed
        {
            get
            {
                return this.steeringBackSpeedField;
            }
            set
            {
                this.steeringBackSpeedField = value;
            }
        }

        /// <remarks/>
        public decimal steeringSensitivity
        {
            get
            {
                return this.steeringSensitivityField;
            }
            set
            {
                this.steeringSensitivityField = value;
            }
        }

        /// <remarks/>
        public byte inputHelpMode
        {
            get
            {
                return this.inputHelpModeField;
            }
            set
            {
                this.inputHelpModeField = value;
            }
        }

        /// <remarks/>
        public bool easyArmControl
        {
            get
            {
                return this.easyArmControlField;
            }
            set
            {
                this.easyArmControlField = value;
            }
        }

        /// <remarks/>
        public bool gyroscopeSteering
        {
            get
            {
                return this.gyroscopeSteeringField;
            }
            set
            {
                this.gyroscopeSteeringField = value;
            }
        }

        /// <remarks/>
        public bool hints
        {
            get
            {
                return this.hintsField;
            }
            set
            {
                this.hintsField = value;
            }
        }

        /// <remarks/>
        public bool cameraTilting
        {
            get
            {
                return this.cameraTiltingField;
            }
            set
            {
                this.cameraTiltingField = value;
            }
        }

        /// <remarks/>
        public byte frameLimit
        {
            get
            {
                return this.frameLimitField;
            }
            set
            {
                this.frameLimitField = value;
            }
        }

        /// <remarks/>
        public bool showAllMods
        {
            get
            {
                return this.showAllModsField;
            }
            set
            {
                this.showAllModsField = value;
            }
        }

        /// <remarks/>
        public string onlinePresenceName
        {
            get
            {
                return this.onlinePresenceNameField;
            }
            set
            {
                this.onlinePresenceNameField = value;
            }
        }

        /// <remarks/>
        public gameSettingsPlayer player
        {
            get
            {
                return this.playerField;
            }
            set
            {
                this.playerField = value;
            }
        }

        /// <remarks/>
        public byte mpLanguage
        {
            get
            {
                return this.mpLanguageField;
            }
            set
            {
                this.mpLanguageField = value;
            }
        }

        /// <remarks/>
        public gameSettingsVolume volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }

        /// <remarks/>
        public gameSettingsSoundPlayer soundPlayer
        {
            get
            {
                return this.soundPlayerField;
            }
            set
            {
                this.soundPlayerField = value;
            }
        }

        /// <remarks/>
        public bool radioIsActive
        {
            get
            {
                return this.radioIsActiveField;
            }
            set
            {
                this.radioIsActiveField = value;
            }
        }

        /// <remarks/>
        public bool radioVehicleOnly
        {
            get
            {
                return this.radioVehicleOnlyField;
            }
            set
            {
                this.radioVehicleOnlyField = value;
            }
        }

        /// <remarks/>
        public gameSettingsVoice voice
        {
            get
            {
                return this.voiceField;
            }
            set
            {
                this.voiceField = value;
            }
        }

        /// <remarks/>
        public gameSettingsUnits units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        public bool isTrainTabbable
        {
            get
            {
                return this.isTrainTabbableField;
            }
            set
            {
                this.isTrainTabbableField = value;
            }
        }

        /// <remarks/>
        public bool showTriggerMarker
        {
            get
            {
                return this.showTriggerMarkerField;
            }
            set
            {
                this.showTriggerMarkerField = value;
            }
        }

        /// <remarks/>
        public bool showHelpTrigger
        {
            get
            {
                return this.showHelpTriggerField;
            }
            set
            {
                this.showHelpTriggerField = value;
            }
        }

        /// <remarks/>
        public bool showFieldInfo
        {
            get
            {
                return this.showFieldInfoField;
            }
            set
            {
                this.showFieldInfoField = value;
            }
        }

        /// <remarks/>
        public bool showHelpIcons
        {
            get
            {
                return this.showHelpIconsField;
            }
            set
            {
                this.showHelpIconsField = value;
            }
        }

        /// <remarks/>
        public bool showHelpMenu
        {
            get
            {
                return this.showHelpMenuField;
            }
            set
            {
                this.showHelpMenuField = value;
            }
        }

        /// <remarks/>
        public bool resetCamera
        {
            get
            {
                return this.resetCameraField;
            }
            set
            {
                this.resetCameraField = value;
            }
        }

        /// <remarks/>
        public bool activeSuspensionCamera
        {
            get
            {
                return this.activeSuspensionCameraField;
            }
            set
            {
                this.activeSuspensionCameraField = value;
            }
        }

        /// <remarks/>
        public bool cameraCheckCollision
        {
            get
            {
                return this.cameraCheckCollisionField;
            }
            set
            {
                this.cameraCheckCollisionField = value;
            }
        }

        /// <remarks/>
        public bool useWorldCamera
        {
            get
            {
                return this.useWorldCameraField;
            }
            set
            {
                this.useWorldCameraField = value;
            }
        }

        /// <remarks/>
        public byte ingameMapState
        {
            get
            {
                return this.ingameMapStateField;
            }
            set
            {
                this.ingameMapStateField = value;
            }
        }

        /// <remarks/>
        public byte ingameMapFilters
        {
            get
            {
                return this.ingameMapFiltersField;
            }
            set
            {
                this.ingameMapFiltersField = value;
            }
        }

        /// <remarks/>
        public byte directionChangeMode
        {
            get
            {
                return this.directionChangeModeField;
            }
            set
            {
                this.directionChangeModeField = value;
            }
        }

        /// <remarks/>
        public byte gearShiftMode
        {
            get
            {
                return this.gearShiftModeField;
            }
            set
            {
                this.gearShiftModeField = value;
            }
        }

        /// <remarks/>
        public byte hudSpeedGauge
        {
            get
            {
                return this.hudSpeedGaugeField;
            }
            set
            {
                this.hudSpeedGaugeField = value;
            }
        }

        /// <remarks/>
        public bool woodHarvesterAutoCut
        {
            get
            {
                return this.woodHarvesterAutoCutField;
            }
            set
            {
                this.woodHarvesterAutoCutField = value;
            }
        }

        /// <remarks/>
        public bool shownFreemodeWarning
        {
            get
            {
                return this.shownFreemodeWarningField;
            }
            set
            {
                this.shownFreemodeWarningField = value;
            }
        }

        /// <remarks/>
        public bool showMultiplayerNames
        {
            get
            {
                return this.showMultiplayerNamesField;
            }
            set
            {
                this.showMultiplayerNamesField = value;
            }
        }

        /// <remarks/>
        public ushort ingameMapGrowthFilter
        {
            get
            {
                return this.ingameMapGrowthFilterField;
            }
            set
            {
                this.ingameMapGrowthFilterField = value;
            }
        }

        /// <remarks/>
        public byte ingameMapSoilFilter
        {
            get
            {
                return this.ingameMapSoilFilterField;
            }
            set
            {
                this.ingameMapSoilFilterField = value;
            }
        }

        /// <remarks/>
        public object ingameMapFruitFilter
        {
            get
            {
                return this.ingameMapFruitFilterField;
            }
            set
            {
                this.ingameMapFruitFilterField = value;
            }
        }

        /// <remarks/>
        public bool useColorblindMode
        {
            get
            {
                return this.useColorblindModeField;
            }
            set
            {
                this.useColorblindModeField = value;
            }
        }

        /// <remarks/>
        public byte maxNumMirrors
        {
            get
            {
                return this.maxNumMirrorsField;
            }
            set
            {
                this.maxNumMirrorsField = value;
            }
        }

        /// <remarks/>
        public byte lightsProfile
        {
            get
            {
                return this.lightsProfileField;
            }
            set
            {
                this.lightsProfileField = value;
            }
        }

        /// <remarks/>
        public decimal fovY
        {
            get
            {
                return this.fovYField;
            }
            set
            {
                this.fovYField = value;
            }
        }

        /// <remarks/>
        public decimal uiScale
        {
            get
            {
                return this.uiScaleField;
            }
            set
            {
                this.uiScaleField = value;
            }
        }

        /// <remarks/>
        public bool realBeaconLights
        {
            get
            {
                return this.realBeaconLightsField;
            }
            set
            {
                this.realBeaconLightsField = value;
            }
        }

        /// <remarks/>
        public bool cameraBobbing
        {
            get
            {
                return this.cameraBobbingField;
            }
            set
            {
                this.cameraBobbingField = value;
            }
        }

        /// <remarks/>
        public gameSettingsPrecisionFarming precisionFarming
        {
            get
            {
                return this.precisionFarmingField;
            }
            set
            {
                this.precisionFarmingField = value;
            }
        }

        /// <remarks/>
        public gameSettingsLastPlayerStyle lastPlayerStyle
        {
            get
            {
                return this.lastPlayerStyleField;
            }
            set
            {
                this.lastPlayerStyleField = value;
            }
        }

        /// <remarks/>
        public gameSettingsLastCreatedLicensePlate lastCreatedLicensePlate
        {
            get
            {
                return this.lastCreatedLicensePlateField;
            }
            set
            {
                this.lastCreatedLicensePlateField = value;
            }
        }

        /// <remarks/>
        public object joinGame
        {
            get
            {
                return this.joinGameField;
            }
            set
            {
                this.joinGameField = value;
            }
        }

        /// <remarks/>
        public gameSettingsCreateGame createGame
        {
            get
            {
                return this.createGameField;
            }
            set
            {
                this.createGameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsModsDirectoryOverride
    {

        private bool activeField;

        private string directoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string directory
        {
            get
            {
                return this.directoryField;
            }
            set
            {
                this.directoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsPlayer
    {

        private bool lastPlayerStyleMaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lastPlayerStyleMale
        {
            get
            {
                return this.lastPlayerStyleMaleField;
            }
            set
            {
                this.lastPlayerStyleMaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsVolume
    {

        private decimal musicField;

        private decimal vehicleField;

        private decimal environmentField;

        private decimal radioField;

        private decimal guiField;

        private decimal voiceField;

        private decimal voiceInputField;

        /// <remarks/>
        public decimal music
        {
            get
            {
                return this.musicField;
            }
            set
            {
                this.musicField = value;
            }
        }

        /// <remarks/>
        public decimal vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }

        /// <remarks/>
        public decimal environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        public decimal radio
        {
            get
            {
                return this.radioField;
            }
            set
            {
                this.radioField = value;
            }
        }

        /// <remarks/>
        public decimal gui
        {
            get
            {
                return this.guiField;
            }
            set
            {
                this.guiField = value;
            }
        }

        /// <remarks/>
        public decimal voice
        {
            get
            {
                return this.voiceField;
            }
            set
            {
                this.voiceField = value;
            }
        }

        /// <remarks/>
        public decimal voiceInput
        {
            get
            {
                return this.voiceInputField;
            }
            set
            {
                this.voiceInputField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsSoundPlayer
    {

        private bool allowStreamsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowStreams
        {
            get
            {
                return this.allowStreamsField;
            }
            set
            {
                this.allowStreamsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsVoice
    {

        private byte modeField;

        private byte inputSensitivityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte inputSensitivity
        {
            get
            {
                return this.inputSensitivityField;
            }
            set
            {
                this.inputSensitivityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsUnits
    {

        private byte moneyField;

        private bool milesField;

        private bool fahrenheitField;

        private bool acreField;

        /// <remarks/>
        public byte money
        {
            get
            {
                return this.moneyField;
            }
            set
            {
                this.moneyField = value;
            }
        }

        /// <remarks/>
        public bool miles
        {
            get
            {
                return this.milesField;
            }
            set
            {
                this.milesField = value;
            }
        }

        /// <remarks/>
        public bool fahrenheit
        {
            get
            {
                return this.fahrenheitField;
            }
            set
            {
                this.fahrenheitField = value;
            }
        }

        /// <remarks/>
        public bool acre
        {
            get
            {
                return this.acreField;
            }
            set
            {
                this.acreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsPrecisionFarming
    {

        private gameSettingsPrecisionFarmingSettings settingsField;

        private bool initializedField;

        /// <remarks/>
        public gameSettingsPrecisionFarmingSettings settings
        {
            get
            {
                return this.settingsField;
            }
            set
            {
                this.settingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool initialized
        {
            get
            {
                return this.initializedField;
            }
            set
            {
                this.initializedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsPrecisionFarmingSettings
    {

        private gameSettingsPrecisionFarmingSettingsInputHelpDisplay inputHelpDisplayField;

        /// <remarks/>
        public gameSettingsPrecisionFarmingSettingsInputHelpDisplay inputHelpDisplay
        {
            get
            {
                return this.inputHelpDisplayField;
            }
            set
            {
                this.inputHelpDisplayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsPrecisionFarmingSettingsInputHelpDisplay
    {

        private bool stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsLastPlayerStyle
    {

        private string filenameField;

        private string beardConfigIdField;

        private byte beardConfigColorField;

        private string bottomConfigIdField;

        private byte bottomConfigColorField;

        private string faceConfigIdField;

        private byte faceConfigColorField;

        private string footwearConfigIdField;

        private byte footwearConfigColorField;

        private string glassesConfigIdField;

        private byte glassesConfigColorField;

        private string hairStyleConfigIdField;

        private byte hairStyleConfigColorField;

        private string headgearConfigIdField;

        private byte headgearConfigColorField;

        private string mustacheConfigIdField;

        private byte mustacheConfigColorField;

        private string topConfigIdField;

        private byte topConfigColorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string beardConfigId
        {
            get
            {
                return this.beardConfigIdField;
            }
            set
            {
                this.beardConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte beardConfigColor
        {
            get
            {
                return this.beardConfigColorField;
            }
            set
            {
                this.beardConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bottomConfigId
        {
            get
            {
                return this.bottomConfigIdField;
            }
            set
            {
                this.bottomConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte bottomConfigColor
        {
            get
            {
                return this.bottomConfigColorField;
            }
            set
            {
                this.bottomConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string faceConfigId
        {
            get
            {
                return this.faceConfigIdField;
            }
            set
            {
                this.faceConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte faceConfigColor
        {
            get
            {
                return this.faceConfigColorField;
            }
            set
            {
                this.faceConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footwearConfigId
        {
            get
            {
                return this.footwearConfigIdField;
            }
            set
            {
                this.footwearConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte footwearConfigColor
        {
            get
            {
                return this.footwearConfigColorField;
            }
            set
            {
                this.footwearConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string glassesConfigId
        {
            get
            {
                return this.glassesConfigIdField;
            }
            set
            {
                this.glassesConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte glassesConfigColor
        {
            get
            {
                return this.glassesConfigColorField;
            }
            set
            {
                this.glassesConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hairStyleConfigId
        {
            get
            {
                return this.hairStyleConfigIdField;
            }
            set
            {
                this.hairStyleConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte hairStyleConfigColor
        {
            get
            {
                return this.hairStyleConfigColorField;
            }
            set
            {
                this.hairStyleConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string headgearConfigId
        {
            get
            {
                return this.headgearConfigIdField;
            }
            set
            {
                this.headgearConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte headgearConfigColor
        {
            get
            {
                return this.headgearConfigColorField;
            }
            set
            {
                this.headgearConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mustacheConfigId
        {
            get
            {
                return this.mustacheConfigIdField;
            }
            set
            {
                this.mustacheConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte mustacheConfigColor
        {
            get
            {
                return this.mustacheConfigColorField;
            }
            set
            {
                this.mustacheConfigColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string topConfigId
        {
            get
            {
                return this.topConfigIdField;
            }
            set
            {
                this.topConfigIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte topConfigColor
        {
            get
            {
                return this.topConfigColorField;
            }
            set
            {
                this.topConfigColorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsLastCreatedLicensePlate
    {

        private byte variationField;

        private byte colorField;

        private byte placementField;

        private string charactersField;

        private string configurationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte variation
        {
            get
            {
                return this.variationField;
            }
            set
            {
                this.variationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte placement
        {
            get
            {
                return this.placementField;
            }
            set
            {
                this.placementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string characters
        {
            get
            {
                return this.charactersField;
            }
            set
            {
                this.charactersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class gameSettingsCreateGame
    {

        private string passwordField;

        private string nameField;

        private ushort portField;

        private bool useUpnpField;

        private bool autoAcceptField;

        private bool allowOnlyFriendsField;

        private bool allowCrossPlayField;

        private byte capacityField;

        private byte bandwidthField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useUpnp
        {
            get
            {
                return this.useUpnpField;
            }
            set
            {
                this.useUpnpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool autoAccept
        {
            get
            {
                return this.autoAcceptField;
            }
            set
            {
                this.autoAcceptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowOnlyFriends
        {
            get
            {
                return this.allowOnlyFriendsField;
            }
            set
            {
                this.allowOnlyFriendsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowCrossPlay
        {
            get
            {
                return this.allowCrossPlayField;
            }
            set
            {
                this.allowCrossPlayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte bandwidth
        {
            get
            {
                return this.bandwidthField;
            }
            set
            {
                this.bandwidthField = value;
            }
        }
    }
}
